blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/sd012gfhkhhvh/dns-resolver/blob/master/README.md
    about: Check the documentation for setup and usage instructions
  - name: 💬 Discussions
    url: https://github.com/sd012gfhkhhvh/dns-resolver/discussions
    about: Ask questions and discuss ideas with the community
